# Default values for splunk-event-reader.
# This is a YAML-formatted file.
service:
  name: "" # The name of the service, should be defined in the specific app-configs folder.
  hasHealthcheck: "true"
eksCluster: false
replicaCount: 2
image:
  repository: coco/splunk-event-reader
  pullPolicy: IfNotPresent
resources:
  requests:
    memory: 300Mi
  limits:
    memory: 550Mi


