{{- if .Values.eksCluster }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: splunk-event-reader
  namespace: default
  type: Opaque
spec:
  encryptedData:
{{ if .Values.encryptedsecrets }}{{ toYaml .Values.encryptedsecrets | indent 4 }}{{ end }}
{{- end }}
